"""Map of the 91 structures from the Institutional Price Action & Liquidity cheat sheet."""
from __future__ import annotations

CATALOG: list[dict] = [
    {"id": 1, "name": "QM Quick Retest", "impl": "composed", "family": "qml"},
    {"id": 2, "name": "QM Late Retest", "impl": "visual", "family": "qml"},
    {"id": 3, "name": "QM Re-Entry", "impl": "visual", "family": "qml"},
    {"id": 4, "name": "Ignored QM / QMTR", "impl": "visual", "family": "qml"},
    {"id": 5, "name": "Continuation QM", "impl": "visual", "family": "qml"},
    {"id": 6, "name": "Reversal at QM", "impl": "composed", "family": "qml"},
    {"id": 7, "name": "QM Shadow", "impl": "visual", "family": "qml"},
    {"id": 8, "name": "Continuation QM", "impl": "visual", "family": "qml"},
    {"id": 9, "name": "2R/2S Fakeout", "impl": "composed", "family": "fakeout"},
    {"id": 10, "name": "V Twin", "impl": "visual", "family": "reversal"},
    {"id": 11, "name": "Flag B", "impl": "visual", "family": "flag"},
    {"id": 12, "name": "Flag A + Flag B", "impl": "visual", "family": "flag"},
    {"id": 13, "name": "Fakeout V1 (Default)", "impl": "composed", "family": "fakeout"},
    {"id": 14, "name": "Fakeout V2 (SR Flip)", "impl": "composed", "family": "fakeout"},
    {"id": 15, "name": "Fakeout V3 (Diamond)", "impl": "visual", "family": "fakeout"},
    {"id": 16, "name": "Double SSR", "impl": "visual", "family": "ssr"},
    {"id": 17, "name": "3 Drive", "impl": "visual", "family": "harmonic"},
    {"id": 18, "name": "Can-Can", "impl": "visual", "family": "named"},
    {"id": 19, "name": "Compression (CP)", "impl": "composed", "family": "compression"},
    {"id": 20, "name": "Compression Liquidity", "impl": "composed", "family": "compression"},
    {"id": 21, "name": "Can-Can + Fakeout", "impl": "visual", "family": "named"},
    {"id": 22, "name": "Ending Diagonal", "impl": "visual", "family": "elliott"},
    {"id": 23, "name": "Ruler (Pembaris)", "impl": "visual", "family": "named"},
    {"id": 24, "name": "R/S Flip", "impl": "composed", "family": "sr"},
    {"id": 25, "name": "Inside Range", "impl": "composed", "family": "range"},
    {"id": 26, "name": "Outside Range", "impl": "composed", "family": "range"},
    {"id": 27, "name": "Triple Top", "impl": "composed", "family": "classic"},
    {"id": 28, "name": "Triple Bottom", "impl": "composed", "family": "classic"},
    {"id": 29, "name": "Demand Zone", "impl": "composed", "family": "zone"},
    {"id": 30, "name": "Supply Zone", "impl": "composed", "family": "zone"},
    {"id": 31, "name": "Order Block (OB)", "impl": "primitive", "family": "ob"},
    {"id": 32, "name": "Breaker Block", "impl": "primitive", "family": "ob"},
    {"id": 33, "name": "Mitigation Block", "impl": "composed", "family": "ob"},
    {"id": 34, "name": "FVG / Imbalance", "impl": "primitive", "family": "fvg"},
    {"id": 35, "name": "Liquidity Void", "impl": "composed", "family": "fvg"},
    {"id": 36, "name": "Premium / Discount", "impl": "primitive", "family": "range"},
    {"id": 37, "name": "Equal Highs (EQH)", "impl": "primitive", "family": "liquidity"},
    {"id": 38, "name": "Equal Lows (EQL)", "impl": "primitive", "family": "liquidity"},
    {"id": 39, "name": "Liquidity Sweep", "impl": "primitive", "family": "liquidity"},
    {"id": 40, "name": "SFP (Swing Failure Pattern)", "impl": "composed", "family": "liquidity"},
    {"id": 41, "name": "Stop Hunt", "impl": "primitive", "family": "liquidity"},
    {"id": 42, "name": "News Liquidity Grab", "impl": "visual", "family": "liquidity"},
    {"id": 43, "name": "Session Liquidity", "impl": "primitive", "family": "session"},
    {"id": 44, "name": "Previous Day Levels", "impl": "primitive", "family": "session"},
    {"id": 45, "name": "Previous Week Levels", "impl": "primitive", "family": "session"},
    {"id": 46, "name": "Trendline Liquidity", "impl": "visual", "family": "liquidity"},
    {"id": 47, "name": "Range High / Low Liquidity", "impl": "composed", "family": "range"},
    {"id": 48, "name": "Displacement + Reclaim", "impl": "composed", "family": "structure"},
    {"id": 49, "name": "Parabolic Blowoff", "impl": "visual", "family": "climax"},
    {"id": 50, "name": "Bear Trap", "impl": "composed", "family": "trap"},
    {"id": 51, "name": "Bull Trap", "impl": "composed", "family": "trap"},
    {"id": 52, "name": "Accumulation", "impl": "visual", "family": "wyckoff"},
    {"id": 53, "name": "Distribution", "impl": "visual", "family": "wyckoff"},
    {"id": 54, "name": "Wyckoff Spring", "impl": "composed", "family": "wyckoff"},
    {"id": 55, "name": "Wyckoff UTAD", "impl": "composed", "family": "wyckoff"},
    {"id": 56, "name": "Wyckoff LPS", "impl": "visual", "family": "wyckoff"},
    {"id": 57, "name": "Inverse H&S", "impl": "composed", "family": "classic"},
    {"id": 58, "name": "Head & Shoulders", "impl": "composed", "family": "classic"},
    {"id": 59, "name": "Double Top", "impl": "composed", "family": "classic"},
    {"id": 60, "name": "Double Bottom", "impl": "composed", "family": "classic"},
    {"id": 61, "name": "Rounding Bottom", "impl": "visual", "family": "classic"},
    {"id": 62, "name": "Rounding Top", "impl": "visual", "family": "classic"},
    {"id": 63, "name": "Descending Triangle", "impl": "composed", "family": "classic"},
    {"id": 64, "name": "Ascending Triangle", "impl": "composed", "family": "classic"},
    {"id": 65, "name": "Symmetrical Triangle", "impl": "visual", "family": "classic"},
    {"id": 66, "name": "Broadening Wedge", "impl": "visual", "family": "classic"},
    {"id": 67, "name": "Falling Wedge", "impl": "visual", "family": "classic"},
    {"id": 68, "name": "Rising Wedge", "impl": "visual", "family": "classic"},
    {"id": 69, "name": "Rectangle / Range", "impl": "composed", "family": "range"},
    {"id": 70, "name": "Diamond Top", "impl": "visual", "family": "classic"},
    {"id": 71, "name": "Diamond Bottom", "impl": "visual", "family": "classic"},
    {"id": 72, "name": "Megaphone", "impl": "visual", "family": "classic"},
    {"id": 73, "name": "Stepping Highs", "impl": "composed", "family": "structure"},
    {"id": 74, "name": "Stepping Lows", "impl": "composed", "family": "structure"},
    {"id": 75, "name": "Elliott 1-2-3-4-5", "impl": "visual", "family": "elliott"},
    {"id": 76, "name": "Elliott A-B-C", "impl": "visual", "family": "elliott"},
    {"id": 77, "name": "Elliott W-X-Y", "impl": "visual", "family": "elliott"},
    {"id": 78, "name": "Liquidity Run (Buy Side)", "impl": "primitive", "family": "liquidity"},
    {"id": 79, "name": "Liquidity Run (Sell Side)", "impl": "primitive", "family": "liquidity"},
    {"id": 80, "name": "Unfilled Wick", "impl": "composed", "family": "wick"},
    {"id": 81, "name": "Gap Fill", "impl": "composed", "family": "fvg"},
    {"id": 82, "name": "Break of Structure (BOS)", "impl": "primitive", "family": "structure"},
    {"id": 83, "name": "Change of Character (CHOCH)", "impl": "primitive", "family": "structure"},
    {"id": 84, "name": "Market Structure Shift (MSS)", "impl": "primitive", "family": "structure"},
    {"id": 85, "name": "Higher Timeframe POI", "impl": "composed", "family": "mtf"},
    {"id": 86, "name": "Multi-Timeframe Confluence", "impl": "composed", "family": "mtf"},
    {"id": 87, "name": "Volume Imbalance", "impl": "visual", "family": "volume"},
    {"id": 88, "name": "Liquidity Pool", "impl": "primitive", "family": "liquidity"},
    {"id": 89, "name": "Retest & Continuation", "impl": "composed", "family": "structure"},
    {"id": 90, "name": "Retest & Reversal", "impl": "composed", "family": "structure"},
    {"id": 91, "name": "Final Shakeout", "impl": "visual", "family": "wyckoff"},
]


def catalog_summary() -> dict[str, int]:
    counts: dict[str, int] = {"primitive": 0, "composed": 0, "visual": 0}
    for row in CATALOG:
        counts[row["impl"]] = counts.get(row["impl"], 0) + 1
    return counts
